name: build jni

on: [push]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jni
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jni/target/classes/lib*
          if-no-files-found: error

  linux-aarch64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: apt update && apt install openjdk-8-jdk g++ -y
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
          maven-arch: aarch64
      - name: Build with Maven
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            cd ${{ github.workspace }}/jni
            mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jni/target/classes/lib*
          if-no-files-found: error

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jni
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jni/target/classes/lib*
          if-no-files-found: error

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jni
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jni/target/classes/*.dll
          if-no-files-found: error
